bundled Percona Toolkit utilities updated to version 3.0.13

diff --git a/bin/pt-mysql-summary b/bin/pt-mysql-summary
--- a/bin/pt-mysql-summary
+++ b/bin/pt-mysql-summary
@@ -75,6 +75,7 @@ HAVE_EXT_ARGV=""  # Got --, everything else is put into EXT_ARGV
 OPT_ERRS=0        # How many command line option errors
 OPT_VERSION=""    # If --version was specified
 OPT_HELP=""       # If --help was specified
+OPT_ASK_PASS=""   # If --ask-pass was specified
 PO_DIR=""         # Directory with program option spec files
 
 usage() {
@@ -175,6 +176,7 @@ parse_options() {
    OPT_ERRS=0
    OPT_VERSION=""
    OPT_HELP=""
+   OPT_ASK_PASS=""
    PO_DIR="$PT_TMPDIR/po"
 
    if [ ! -d "$PO_DIR" ]; then
@@ -203,7 +205,10 @@ parse_options() {
          _parse_config_files "$user_config_file"
       done
    else
-      _parse_config_files "/etc/percona-toolkit/percona-toolkit.conf" "/etc/percona-toolkit/$TOOL.conf" "$HOME/.percona-toolkit.conf" "$HOME/.$TOOL.conf"
+      _parse_config_files "/etc/percona-toolkit/percona-toolkit.conf" "/etc/percona-toolkit/$TOOL.conf"
+      if [ "${HOME:-}" ]; then
+         _parse_config_files "$HOME/.percona-toolkit.conf" "$HOME/.$TOOL.conf"
+      fi
    fi
 
    _parse_command_line "${@:-""}"
@@ -309,7 +314,7 @@ _parse_config_files() {
 
          echo "$config_opt" | grep '^[ ]*[^#]' >/dev/null 2>&1 || continue
 
-         config_opt="$(echo "$config_opt" | sed -e 's/^ *//g' -e 's/ *$//g' -e 's/[ ]*=[ ]*/=/' -e 's/[ ]*#.*$//')"
+         config_opt="$(echo "$config_opt" | sed -e 's/^ *//g' -e 's/ *$//g' -e 's/[ ]*=[ ]*/=/' -e 's/[ ]+#.*$//')"
 
          [ "$config_opt" = "" ] && continue
 
@@ -486,7 +491,14 @@ mysql_options() {
    if [ -n "$OPT_USER" ]; then
       MYSQL_ARGS="$MYSQL_ARGS --user=$OPT_USER"
    fi
-   if [ -n "$OPT_PASSWORD" ]; then
+   if [ -n "$OPT_ASK_PASS" ]; then
+      stty -echo
+      >&2 printf "Enter MySQL password: "
+      read GIVEN_PASS 
+      stty echo
+      printf "\n"
+      MYSQL_ARGS="$MYSQL_ARGS --password=$GIVEN_PASS"
+   elif [ -n "$OPT_PASSWORD" ]; then
       MYSQL_ARGS="$MYSQL_ARGS --password=$OPT_PASSWORD"
    fi
    
@@ -815,7 +827,7 @@ setup_data_dir () {
 get_var () {
    local varname="$1"
    local file="$2"
-   awk -v pattern="${varname}" '$1 == pattern { if (length($2)) { len = length($1); print substr($0, len+index(substr($0, len+1), $2)) } }' "${file}"
+   awk -v pattern="${varname}" '$1 == pattern { if (length($2)) { len = length($1); print substr($0, len+index(substr($0, len+1), $2)) } }' "${file}" | tr -d '\r'
 }
 
 # ###########################################################################
@@ -909,12 +921,28 @@ collect_mysql_innodb_status () {
    $CMD_MYSQL $EXT_ARGV -ssE -e 'SHOW /*!50000 ENGINE*/ INNODB STATUS' 2>/dev/null
 }
 
+collect_mysql_ndb_status () {
+   $CMD_MYSQL $EXT_ARGV -ssE -e 'show /*!50000 ENGINE*/ NDB STATUS' 2>/dev/null
+}
+
 collect_mysql_processlist () {
    $CMD_MYSQL $EXT_ARGV -ssE -e 'SHOW FULL PROCESSLIST' 2>/dev/null
 }
 
 collect_mysql_users () {
    $CMD_MYSQL $EXT_ARGV -ss -e 'SELECT COUNT(*), SUM(user=""), SUM(password=""), SUM(password NOT LIKE "*%") FROM mysql.user' 2>/dev/null
+   if [ "$?" -ne 0 ]; then
+       $CMD_MYSQL $EXT_ARGV -ss -e 'SELECT COUNT(*), SUM(user=""), SUM(authentication_string=""), SUM(authentication_string NOT LIKE "*%") FROM mysql.user WHERE account_locked <> "Y" AND password_expired <> "Y" AND authentication_string <> ""' 2>/dev/null
+   fi
+}
+
+collect_mysql_roles () {
+   QUERY="SELECT DISTINCT User 'Role Name', if(from_user is NULL,0, 1) Active FROM mysql.user LEFT JOIN mysql.role_edges ON from_user=user WHERE account_locked='Y' AND password_expired='Y' AND authentication_string=''\G"
+   $CMD_MYSQL $EXT_ARGV -ss -e "$QUERY" 2>/dev/null
+}
+
+collect_mysql_show_slave_hosts () {
+   $CMD_MYSQL $EXT_ARGV -ssE -e 'SHOW SLAVE HOSTS' 2>/dev/null
 }
 
 collect_master_logs_status () {
@@ -1010,11 +1038,14 @@ collect_mysql_info () {
    collect_mysql_plugins       > "$dir/mysql-plugins"
    collect_mysql_slave_status  > "$dir/mysql-slave"
    collect_mysql_innodb_status > "$dir/innodb-status"
+   collect_mysql_ndb_status    > "$dir/ndb-status"
    collect_mysql_processlist   > "$dir/mysql-processlist"   
    collect_mysql_users         > "$dir/mysql-users"
+   collect_mysql_roles         > "$dir/mysql-roles"
 
    collect_mysqld_instances   "$dir/mysql-variables"  > "$dir/mysqld-instances"
    collect_mysqld_executables "$dir/mysqld-instances" > "$dir/mysqld-executables"
+   collect_mysql_show_slave_hosts  "$dir/mysql-slave-hosts" > "$dir/mysql-slave-hosts"
 
    local binlog="$(get_var log_bin "$dir/mysql-variables")"
    if [ "${binlog}" ]; then
@@ -1145,6 +1176,19 @@ get_plugin_status () {
 
    echo ${status:-"Not found"}
 }
+
+collect_keyring_plugins() {
+    $CMD_MYSQL $EXT_ARGV --table -ss -e 'SELECT PLUGIN_NAME, PLUGIN_STATUS FROM INFORMATION_SCHEMA.PLUGINS WHERE PLUGIN_NAME LIKE "keyring%";'
+}
+
+collect_encrypted_tables() {
+    $CMD_MYSQL $EXT_ARGV --table -ss -e "SELECT TABLE_SCHEMA, TABLE_NAME, CREATE_OPTIONS FROM INFORMATION_SCHEMA.TABLES WHERE CREATE_OPTIONS LIKE '%ENCRYPTION=\"Y\"%';"
+}
+
+collect_encrypted_tablespaces() {
+    $CMD_MYSQL $EXT_ARGV --table -ss -e "SELECT SPACE, NAME, SPACE_TYPE from INFORMATION_SCHEMA.INNODB_SYS_TABLESPACES where FLAG&8192 = 8192;"
+}
+
 
 
 _NO_FALSE_NEGATIVES=""
@@ -1322,6 +1366,9 @@ summarize_processlist () {
          }
          \$1 == \"Time:\" {
             t = \$2;
+            if ( t == \"NULL\" ) { 
+                t = 0;
+            }
          }
          \$1 == \"Command:\" {
             c = \$2;
@@ -1357,7 +1404,7 @@ pretty_print_cnf_file () {
 
    perl -n -l -e '
       my $line = $_;
-      if ( $line =~ /^[ \t]*[a-zA-Z[]/ ) { 
+      if ( $line =~ /^\s*[a-zA-Z[]/ ) { 
          if ( $line=~/\s*(.*?)\s*=\s*(.*)\s*$/ ) { 
             printf("%-35s = %s\n", $1, $2)  
          } 
@@ -1369,6 +1416,7 @@ pretty_print_cnf_file () {
       }' "$file"
 
 }
+
 
 find_checkpoint_age() {
    local file="$1"
@@ -1557,6 +1605,50 @@ format_innodb_status () {
       grep -e 'Mutex at' -e 'lock on' "${file}" | sed -e 's/^[XS]-//' -e 's/,.*$//' \
          | sort | uniq -c | sort -rn
    fi
+}
+
+format_ndb_status() {
+   local file=$1
+
+   [ -e "$file" ] || return
+   egrep '^[ \t]*Name:|[ \t]*Status:' $file|sed 's/^[ \t]*//g'|while read line; do echo $line; echo $line | grep '^Status:'>/dev/null && echo ; done
+}
+
+format_keyring_plugins() {
+    local keyring_plugins="$1"
+    local encrypted_tables="$2"
+
+    if [ -z "$keyring_plugins" ]; then 
+        echo "No keyring plugins found"
+        if [ ! -z "$encrypted_tables" ]; then
+            echo "Warning! There are encrypted tables but keyring plugins are not loaded"
+        fi
+     else
+        echo "Keyring plugins:"
+        echo "'$keyring_plugins'"
+    fi
+}
+
+format_encrypted_tables() {
+   local encrypted_tables="$1"
+   if [ ! -z "$encrypted_tables" ]; then
+       echo "Encrypted tables:"
+       echo "$encrypted_tables"
+   fi
+}
+
+format_encrypted_tablespaces() {
+   local encrypted_tablespaces="$1"
+   if [ ! -z "$encrypted_tablespaces" ]; then
+       echo "Encrypted tablespaces:"
+       echo "$encrypted_tablespaces"
+   fi
+}
+
+format_mysql_roles() {
+   local file=$1
+   [ -e "$file" ] || return
+   cat $file
 }
 
 format_overall_db_stats () {
@@ -1961,6 +2053,32 @@ section_innodb () {
             "$(get_var innodb_adaptive_checkpoint "$variables_file")"
 }
 
+section_rocksdb () {
+    local variables_file="$1"
+    local status_file="$2"
+
+    local NAME_VAL_LEN=32
+
+    [ -e "$variables_file" -a -e "$status_file" ] || return
+
+    name_val "Block Cache Size" "$(shorten $(get_var rocksdb_block_cache_size "$variables_file") 0)"
+    name_val "Block Size" "$(shorten $(get_var rocksdb_block_size "$variables_file") 0)"
+    name_val "Bytes Per Sync" "$(shorten $(get_var rocksdb_bytes_per_sync "$variables_file") 0)"
+    name_val "Compaction Seq Deletes " "$(shorten $(get_var rocksdb_compaction_sequential_deletes "$variables_file") 0)"
+    name_val "Compaction Seq Deletes Count SD" "$(get_var rocksdb_compaction_sequential_deletes_count_sd "$variables_file")"
+    name_val "Compaction Seq Deletes Window" "$(shorten $(get_var rocksdb_compaction_sequential_deletes_window "$variables_file") 0)"
+    name_val "Default CF Options" "$(get_var rocksdb_default_cf_options "$variables_file")"
+    name_val "Max Background Jobs" "$(shorten $(get_var rocksdb_max_background_jobs "$variables_file") 0)"
+    name_val "Max Block Cache Size" "$(shorten $(get_var rocksdb_max_block_cache_size "$variables_file") 0)"
+    name_val "Max Block Size" "$(shorten $(get_var rocksdb_max_block_size "$variables_file") 0)"
+    name_val "Max Open Files" "$(shorten $(get_var rocksdb_max_open_files "$variables_file") 0)"
+    name_val "Max Total Wal Size" "$(shorten $(get_var rocksdb_max_total_wal_size "$variables_file") 0)"
+    name_val "Rate Limiter Bytes Per Second" "$(shorten $(get_var rocksdb_rate_limiter_bytes_per_sec "$variables_file") 0)"
+    name_val "Rate Limiter Bytes Per Sync" "$(shorten $(get_var rocksdb_bytes_per_sync "$variables_file") 0)"
+    name_val "Rate Limiter Wal Bytes Per Sync" "$(shorten $(get_var rocksdb_wal_bytes_per_sync "$variables_file") 0)"
+    name_val "Table Cache NumHardBits" "$(shorten $(get_var rocksdb_table_cache_numshardbits "$variables_file") 0)"
+    name_val "Wal Bytes per Sync" "$(shorten $(get_var rocksdb_wal_bytes_per_sync "$variables_file") 0)"
+}
 
 section_noteworthy_variables () {
    local file="$1"
@@ -2080,6 +2198,19 @@ section_mysqld () {
    done < "$executables_file"
 }
 
+section_slave_hosts () {
+   local slave_hosts_file="$1"
+
+   [ -e "$slave_hosts_file" ] || return
+
+   section "Slave Hosts"
+   if [ -s "$slave_hosts_file" ]; then
+       cat "$slave_hosts_file"
+   else
+       echo "No slaves found"
+   fi
+}
+
 section_mysql_files () {
    local variables_file="$1"
 
@@ -2132,6 +2263,33 @@ parse_wsrep_provider_options () {
    ' "$looking_for"
 }
 
+report_jemalloc_enabled() {
+  local JEMALLOC_STATUS=''
+  local GENERAL_JEMALLOC_STATUS=0
+  local JEMALLOC_LOCATION=''
+
+  for pid in $(pidof mysqld); do
+     grep -qc jemalloc /proc/${pid}/environ || ldd $(which mysqld) 2>/dev/null | grep -qc jemalloc
+     jemalloc_status=$?
+     if [ $jemalloc_status = 1 ]; then
+       echo "jemalloc is not enabled in mysql config for process with id ${pid}" 
+     else
+       echo "jemalloc enabled in mysql config for process with id ${pid}"
+       GENERAL_JEMALLOC_STATUS=1
+     fi
+  done
+
+  if [ $GENERAL_JEMALLOC_STATUS -eq 1 ]; then
+     JEMALLOC_LOCATION=$(find /usr/lib64/ /usr/lib/x86_64-linux-gnu /usr/lib -name "libjemalloc.*" 2>/dev/null | head -n 1)
+     if [ -z "$JEMALLOC_LOCATION" ]; then
+       echo "Jemalloc library not found"
+     else
+       echo "Using jemalloc from $JEMALLOC_LOCATION"
+     fi
+  fi
+ 
+}
+
 report_mysql_summary () {
    local dir="$1"
 
@@ -2145,6 +2303,7 @@ report_mysql_summary () {
 
    section_mysqld "$dir/mysqld-executables" "$dir/mysql-variables"
 
+   section_slave_hosts "$dir/mysql-slave-hosts"
    local user="$(get_var "pt-summary-internal-user" "$dir/mysql-variables")"
    local port="$(get_var port "$dir/mysql-variables")"
    local now="$(get_var "pt-summary-internal-now" "$dir/mysql-variables")"
@@ -2212,7 +2371,8 @@ report_mysql_summary () {
    section "Plugins"
    name_val "InnoDB compression" "$(get_plugin_status "$dir/mysql-plugins" "INNODB_CMP")"
 
-   if [ "$(get_var have_query_cache "$dir/mysql-variables")" ]; then
+   local has_query_cache=$(get_var have_query_cache "$dir/mysql-variables")
+   if [ "$has_query_cache" = 'YES' ]; then
       section "Query cache"
       local query_cache_size=$(get_var query_cache_size "$dir/mysql-variables")
       local used=$(( ${query_cache_size} - $(get_var Qcache_free_memory "$dir/mysql-status") ))
@@ -2327,9 +2487,21 @@ report_mysql_summary () {
    local innodb_version="$(get_var "innodb_version" "$dir/mysql-variables")"
    if [ "${have_innodb}" = "YES" ] || [ -n "${innodb_version}" ]; then
       section_innodb "$dir/mysql-variables" "$dir/mysql-status"
+
       if [ -s "$dir/innodb-status" ]; then
          format_innodb_status "$dir/innodb-status"
       fi
+   fi
+
+   local has_rocksdb=$($CMD_MYSQL $EXT_ARGV -ss -e 'SHOW ENGINES' 2>/dev/null | grep -i 'rocksdb')
+   if [ ! -z "$has_rocksdb" ]; then
+       section "RocksDB"
+       section_rocksdb "$dir/mysql-variables" "$dir/mysql-status"
+   fi
+
+   if [ -s "$dir/ndb-status" ]; then
+       section "NDB"
+       format_ndb_status "$dir/ndb-status"
    fi
 
    section "MyISAM"
@@ -2339,6 +2511,24 @@ report_mysql_summary () {
    local users="$( format_users "$dir/mysql-users" )"
    name_val "Users" "${users}"
    name_val "Old Passwords" "$(get_var old_passwords "$dir/mysql-variables")"
+
+   if [ -s "$dir/mysql-roles" ]; then
+       section "Roles"
+       format_mysql_roles "$dir/mysql-roles"
+   fi
+
+   section "Encryption"
+   local keyring_plugins="$(collect_keyring_plugins)"
+   local encrypted_tables=""
+   local encrypted_tablespaces=""
+   if [ "${OPT_LIST_ENCRYPTED_TABLES}" = 'yes' ]; then 
+       encrypted_tables="$(collect_encrypted_tables)"
+       encrypted_tablespaces="$(collect_encrypted_tablespaces)"
+   fi
+
+   format_keyring_plugins "$keyring_plugins" "$encrypted_tables"
+   format_encrypted_tables "$encrypted_tables"
+   format_encrypted_tablespaces "$encrypted_tablespaces"
 
    section "Binary Logging"
 
@@ -2367,6 +2557,9 @@ report_mysql_summary () {
       name_val "Config File" "Cannot autodetect or find, giving up"
    fi
 
+   section "Memory management library"
+   report_jemalloc_enabled
+
    section "The End"
 }
 
@@ -2390,14 +2583,14 @@ check_mysql () {
    # Check that mysql and mysqldump are in PATH.  If not, we're
    # already dead in the water, so don't bother with cmd line opts,
    # just error and exit.
-   [ -n "$(mysql --help 2>/dev/null)" ] \
+   [ -n "$(${CMD_MYSQL} --help 2>/dev/null)" ] \
       || die "Cannot execute mysql.  Check that it is in PATH."
-   [ -n "$(mysqldump --help 2>/dev/null)" ] \
+   [ -n "$(${CMD_MYSQLDUMP} --help 2>/dev/null)" ] \
       || die "Cannot execute mysqldump.  Check that it is in PATH."
 
    # Now that we have the cmd line opts, check that we can actually
    # connect to MySQL.
-   [ -n "$(mysql $EXT_ARGV -e 'SELECT 1')" ] \
+   [ -n "$(${CMD_MYSQL} ${EXT_ARGV} -e 'SHOW STATUS')" ] \
       || die "Cannot connect to MySQL.  Check that MySQL is running and that the options after -- are correct."
 
 }
@@ -2920,6 +3113,10 @@ All options after -- are passed to C<mysql>.
 
 mysqldump and summarize all databases.  See L<"--databases">.
 
+=item --ask-pass
+
+Prompt for a password when connecting to MySQL.
+
 =item --config
 
 type: string
@@ -2951,11 +3148,19 @@ short form: -h; type: string
 
 Host to connect to.
 
+=item --list-encrypted-tables
+
+default: false
+
+Include a list of the encrypted tables in all databases. This can cause slowdowns since
+querying Information Schema tables can be slow.
+
 =item --password
 
 short form: -p; type: string
 
 Password to use when connecting.
+If password contains commas they must be escaped with a backslash: "exam\,ple"
 
 =item --port
 
@@ -3013,7 +3218,7 @@ On BSD systems, it may require a mounted procfs.
 
 For a list of known bugs, see L<http://www.percona.com/bugs/pt-mysql-summary>.
 
-Please report bugs at L<https://bugs.launchpad.net/percona-toolkit>.
+Please report bugs at L<https://jira.percona.com/projects/PT>.
 Include the following information in your bug report:
 
 =over
@@ -3066,7 +3271,7 @@ software from Percona.
 
 =head1 COPYRIGHT, LICENSE, AND WARRANTY
 
-This program is copyright 2011-2014 Percona LLC and/or its affiliates,
+This program is copyright 2011-2018 Percona LLC and/or its affiliates,
 2010-2011 Baron Schwartz.
 
 THIS PROGRAM IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED
@@ -3085,7 +3290,7 @@ Place, Suite 330, Boston, MA  02111-1307  USA.
 
 =head1 VERSION
 
-pt-mysql-summary 2.2.12
+pt-mysql-summary 3.0.13
 
 =cut
 
